import re
from pathlib import Path
from typing import Any

import duckdb

from app.data.sql_loader import load_sql_directory


def safe_name(value: str) -> str:
    name = re.sub(r"[^a-zA-Z0-9_]+", "_", value.strip().lower()).strip("_")
    if not name or name[0].isdigit():
        name = f"dataset_{name}"
    return name


class DatasetCatalog:
    """Discovers CSVs and exposes only assistant-safe semantic datasets.

    When the final TBX bank/account/transaction trio is present, the source
    files are registered privately and joined into public views that omit UTRs
    and replace full account numbers with their last four characters. Other
    CSV layouts retain the generic discovery path for local experimentation.
    """

    def __init__(self, directory: str):
        self.directory = Path(directory)
        self.directory.mkdir(parents=True, exist_ok=True)

    # Identifier columns look numeric to DuckDB's sniffer whenever the sample
    # happens to be all digits. Once inferred as BIGINT, the first comparison
    # against a string id raises a conversion error and takes the request with
    # it. Reading them as VARCHAR costs nothing and removes the whole class.
    ID_COLUMN_RE = re.compile(r"(^|_)(id|ids|code|codes|ref|refs|number|no)$", re.IGNORECASE)

    def _forced_varchar(self, path: Path) -> dict[str, str]:
        try:
            header = path.open("r", encoding="utf-8", errors="ignore").readline()
        except OSError:
            return {}
        columns = [c.strip().strip('"').lower().replace(" ", "_") for c in header.split(",")]
        return {c: "VARCHAR" for c in columns if c and self.ID_COLUMN_RE.search(c)}

    def connection(self) -> duckdb.DuckDBPyConnection:
        connection = duckdb.connect(":memory:")
        paths = sorted(self.directory.glob("*.csv"))

        # TBX ships SQL, not CSV: CREATE TABLE plus INSERT blocks, sometimes
        # inside a schema document. Loaded under the same _source_ prefix so the
        # safe views below cover it identically.
        sql_tables = load_sql_directory(connection, self.directory, prefix="_source_")

        csv_names = {safe_name(path.stem) for path in paths}
        final_schema = (csv_names | set(sql_tables)) >= {"bank", "account", "transaction"}
        for path in paths:
            view = safe_name(path.stem)
            registered_view = f"_source_{view}" if final_schema else view
            escaped = str(path.resolve()).replace("'", "''")
            forced = self._forced_varchar(path)
            # DuckDB rejects an empty types={} with a parser error, so omit it
            types = f", types={forced!r}" if forced else ""
            connection.execute(
                f'CREATE VIEW "{registered_view}" AS SELECT * FROM '
                f"read_csv_auto('{escaped}', normalize_names=true{types})"
            )
        if final_schema:
            self._create_tbx_views(connection)
        return connection

    @staticmethod
    def _create_tbx_views(connection: duckdb.DuckDBPyConnection) -> None:
        """Final TBX schema mapped to safe, single-table query surfaces.

        Joins are deterministic here rather than generated by the LLM. Raw
        account_number and utr_number never enter the planner catalog, result
        rows, exports, or the low-cardinality vocabulary cache.
        """
        connection.execute('''
            CREATE VIEW bank AS
            SELECT CAST(bank_code AS VARCHAR) AS bank_code,
                   CAST(bank_name AS VARCHAR) AS bank_name
            FROM _source_bank
        ''')
        connection.execute('''
            CREATE VIEW account AS
            SELECT CAST(a.account_id AS VARCHAR) AS account_id,
                   CAST(a.entity_id AS VARCHAR) AS entity_id,
                   RIGHT(CAST(a.account_number AS VARCHAR), 4) AS account_last4,
                   a.program_id,
                   a.available_balance,
                   CAST(a.bank_code AS VARCHAR) AS bank_code,
                   CAST(b.bank_name AS VARCHAR) AS bank_name
            FROM _source_account a
            LEFT JOIN _source_bank b ON a.bank_code = b.bank_code
        ''')
        connection.execute('''
            CREATE VIEW "transaction" AS
            SELECT CAST(t.transaction_id AS VARCHAR) AS transaction_id,
                   CAST(t.account_id AS VARCHAR) AS account_id,
                   CAST(a.entity_id AS VARCHAR) AS entity_id,
                   CAST(a.bank_code AS VARCHAR) AS bank_code,
                   CAST(b.bank_name AS VARCHAR) AS bank_name,
                   a.program_id,
                   RIGHT(CAST(a.account_number AS VARCHAR), 4) AS account_last4,
                   t.transaction_date,
                   CAST(t.transaction_type AS VARCHAR) AS transaction_type,
                   CAST(t.description AS VARCHAR) AS description,
                   t.transaction_amount,
                   CAST(t.transaction_reference_id AS VARCHAR) AS transaction_reference_id,
                   (t.utr_number IS NOT NULL AND LENGTH(TRIM(CAST(t.utr_number AS VARCHAR))) > 0)
                       AS utr_available,
                   -- ledger direction: "spend" means debits, and summing
                   -- transaction_amount would add money in to money out
                   CASE WHEN LOWER(t.transaction_type) = 'debit'
                        THEN t.transaction_amount ELSE 0 END AS debit_amount,
                   CASE WHEN LOWER(t.transaction_type) = 'credit'
                        THEN t.transaction_amount ELSE 0 END AS credit_amount,
                   CASE WHEN LOWER(t.transaction_type) = 'debit'
                        THEN -t.transaction_amount ELSE t.transaction_amount END AS signed_amount,
                   -- The schema carries no reconciliation column. A transaction
                   -- with nothing to match against is what an operations team
                   -- calls unreconciled, so that is the definition used - and the
                   -- assistant states it whenever it answers such a question.
                   CASE WHEN t.transaction_reference_id IS NULL
                             AND (t.utr_number IS NULL OR LENGTH(TRIM(CAST(t.utr_number AS VARCHAR))) = 0)
                        THEN 'unreconciled'
                        WHEN t.transaction_reference_id IS NULL
                             OR t.utr_number IS NULL
                             OR LENGTH(TRIM(CAST(t.utr_number AS VARCHAR))) = 0
                        THEN 'partially_reconciled'
                        ELSE 'reconciled' END AS reconciliation_status
            FROM _source_transaction t
            LEFT JOIN _source_account a ON t.account_id = a.account_id
            LEFT JOIN _source_bank b ON a.bank_code = b.bank_code
        ''')

    def describe(self) -> dict[str, list[dict[str, str]]]:
        connection = self.connection()
        catalog: dict[str, list[dict[str, str]]] = {}
        for (name,) in connection.execute("SHOW TABLES").fetchall():
            if name.startswith("_source_"):
                continue
            rows = connection.execute(f'DESCRIBE "{name}"').fetchall()
            catalog[name] = [{"name": row[0], "type": row[1]} for row in rows]
        connection.close()
        return catalog

    def date_bounds(self) -> tuple[str | None, str | None]:
        """Earliest and latest date anywhere in the loaded data.

        Relative periods must anchor here, not to datetime.today(). A finance
        dataset is historical: if it ends in June and today is September, "last
        month" against the wall clock selects an empty window and the assistant
        confidently answers zero. Anchoring to the data makes "last month" mean
        the last month the data actually has.
        """
        connection = self.connection()
        lo: str | None = None
        hi: str | None = None
        try:
            for (table,) in connection.execute("SHOW TABLES").fetchall():
                for row in connection.execute(f'DESCRIBE "{table}"').fetchall():
                    column, column_type = row[0], row[1].upper()
                    if "DATE" not in column_type and "TIMESTAMP" not in column_type:
                        continue
                    try:
                        low, high = connection.execute(
                            f'SELECT MIN("{column}"), MAX("{column}") FROM "{table}"'
                        ).fetchone()
                    except duckdb.Error:
                        continue
                    for value in (low, high):
                        if value is None:
                            continue
                        text = str(value)[:10]
                        lo = text if lo is None or text < lo else lo
                        hi = text if hi is None or text > hi else hi
        finally:
            connection.close()
        return lo, hi

    def column_date_bounds(self) -> dict[str, tuple[str, str]]:
        """Bounds for every date column, keyed "table.column".

        Per column, not global: an audit field like last_reviewed_at can run
        weeks past the last payout_date, and anchoring "last month" to the
        global maximum then selects a month the payouts table does not reach.
        """
        connection = self.connection()
        bounds: dict[str, tuple[str, str]] = {}
        try:
            for (table,) in connection.execute("SHOW TABLES").fetchall():
                for row in connection.execute(f'DESCRIBE "{table}"').fetchall():
                    column, column_type = row[0], row[1].upper()
                    if "DATE" not in column_type and "TIMESTAMP" not in column_type:
                        continue
                    try:
                        low, high = connection.execute(
                            f'SELECT MIN("{column}"), MAX("{column}") FROM "{table}"'
                        ).fetchone()
                    except duckdb.Error:
                        continue
                    if low is not None and high is not None:
                        bounds[f"{table}.{column}"] = (str(low)[:10], str(high)[:10])
        finally:
            connection.close()
        return bounds

    def save_upload(self, filename: str, content: bytes) -> str:
        if not filename.lower().endswith(".csv"):
            raise ValueError("Only CSV files are accepted in the starter")
        destination = self.directory / f"{safe_name(Path(filename).stem)}.csv"
        destination.write_bytes(content)
        return destination.name
